// Why: agent harnesses (Claude Code and its forks) inject machinery into the
// conversation as user-role turns — background task notifications, system
// reminders, slash-command envelopes, local-command output, interruption and
// compaction notices. These fire user-prompt hooks and land in transcripts,
// but they are not something the user typed, so prompt-derived UI must not
// surface them.
const HARNESS_INJECTED_TURN_PREFIXES = [
  '<task-notification>',
  '<system-reminder>',
  '<local-command-stdout>',
  '<local-command-caveat>',
  '<command-name>',
  '<command-message>',
  '<command-args>',
  '<bash-',
  '[request interrupted',
  'caveat: the messages below were generated by the user while running local commands',
  'this session is being continued from a previous conversation'
]

/** True when prompt-like text is a harness-injected machinery turn rather
 *  than something the user typed. Prefix match on trimmed, lowercased text. */
export function isHarnessInjectedUserTurnText(text: string): boolean {
  const normalized = text.trim().toLowerCase()
  if (normalized.length === 0) {
    return false
  }
  return HARNESS_INJECTED_TURN_PREFIXES.some((prefix) => normalized.startsWith(prefix))
}
